server:
  port: 0

spring:
  application:
    name: user-service

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true # EUREKA 서버로부터 인스턴스들의 정보를 주기적으로 가져온다고 설정
    fetch-registry: true
    service-url:
      defaultZone: http://172.30.1.43:8761/eureka

